services:
  zookeeper:
    image: "docker.io/bitnami/zookeeper:3"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
 
  kafka:
    image: "docker.io/bitnami/kafka:2-debian-10"
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

  manager:
    build: ./iot-manager
    depends_on:
      - kafka
    ports:
      - 3000:3000
    command: npm start run

  sensor1:
    build: ./iot-sensor
    environment:
      - SENSOR_ID=1
    command: npm start run

  sensor2:
    build: ./iot-sensor
    environment:
      - SENSOR_ID=1
    command: npm start run

  sensor3:
    build: ./iot-sensor
    environment:
      - SENSOR_ID=1
    command: npm start run

  sensor4:
    build: ./iot-sensor
    environment:
      - SENSOR_ID=1
    command: npm start run